/**
 * Project Scaffold
 *
 * Wraps generated code files into a complete, runnable Next.js project
 * structure with all necessary configuration files.
 */

import type { GeneratedCodeOutput } from './code-generator'

export interface ScaffoldMetadata {
  appName: string
  description: string
}

/**
 * Scaffold a complete Next.js project from generated code output.
 * Returns a Record<filepath, content> suitable for zip creation.
 */
export function scaffoldProject(
  code: GeneratedCodeOutput,
  metadata?: ScaffoldMetadata
): Record<string, string> {
  const appName = metadata?.appName || code.appName || 'fhir-app'
  const description = metadata?.description || code.description || 'A FHIR healthcare application'
  const files: Record<string, string> = {}

  // package.json
  files['package.json'] = JSON.stringify({
    name: appName,
    version: '0.1.0',
    private: true,
    scripts: {
      dev: 'next dev',
      build: 'next build',
      start: 'next start',
      lint: 'next lint',
    },
    dependencies: {
      '@medplum/core': '^3.2.0',
      '@medplum/fhirtypes': '^3.2.0',
      '@medplum/react': '^3.2.0',
      next: '14.2.0',
      react: '^18.3.0',
      'react-dom': '^18.3.0',
    },
    devDependencies: {
      '@types/node': '^20',
      '@types/react': '^18',
      '@types/react-dom': '^18',
      typescript: '^5',
      tailwindcss: '^3.4.0',
      postcss: '^8',
      autoprefixer: '^10',
    },
  }, null, 2)

  // tsconfig.json
  files['tsconfig.json'] = JSON.stringify({
    compilerOptions: {
      target: 'es5',
      lib: ['dom', 'dom.iterable', 'esnext'],
      allowJs: true,
      skipLibCheck: true,
      strict: true,
      noEmit: true,
      esModuleInterop: true,
      module: 'esnext',
      moduleResolution: 'bundler',
      resolveJsonModule: true,
      isolatedModules: true,
      jsx: 'preserve',
      incremental: true,
      plugins: [{ name: 'next' }],
      paths: { '@/*': ['./src/*'] },
    },
    include: ['next-env.d.ts', '**/*.ts', '**/*.tsx', '.next/types/**/*.ts'],
    exclude: ['node_modules'],
  }, null, 2)

  // next.config.ts
  files['next.config.ts'] = `import type { NextConfig } from 'next'

const nextConfig: NextConfig = {}

export default nextConfig
`

  // tailwind.config.ts
  files['tailwind.config.ts'] = `import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {},
  },
  plugins: [],
}

export default config
`

  // postcss.config.mjs
  files['postcss.config.mjs'] = `/** @type {import('postcss-load-config').Config} */
const config = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
}

export default config
`

  // .env.example
  files['.env.example'] = `# Medplum FHIR Server Configuration
NEXT_PUBLIC_MEDPLUM_BASE_URL=https://api.medplum.com
NEXT_PUBLIC_MEDPLUM_CLIENT_ID=your-client-id
`

  // src/app/globals.css
  files['src/app/globals.css'] = `@tailwind base;
@tailwind components;
@tailwind utilities;
`

  // src/app/layout.tsx
  files['src/app/layout.tsx'] = `import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: '${appName}',
  description: '${description}',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
`

  // README.md
  files['README.md'] = `# ${appName}

${description}

Generated by [FHIRBuilders OpenClaw](https://fhirbuilders.com).

## Getting Started

1. Install dependencies:
   \`\`\`bash
   npm install
   \`\`\`

2. Copy the environment file and configure:
   \`\`\`bash
   cp .env.example .env.local
   \`\`\`

3. Run the development server:
   \`\`\`bash
   npm run dev
   \`\`\`

4. Open [http://localhost:3000](http://localhost:3000) in your browser.

## FHIR Resources

This app uses the Medplum SDK to interact with FHIR R4 resources.
You need a Medplum account to connect to a live FHIR server.

Visit [medplum.com](https://www.medplum.com) to get started.
`

  // Add generated component files
  if (code.components) {
    for (const component of code.components) {
      files[component.path] = component.code
    }
  }

  // Add generated page files
  if (code.pages) {
    for (const page of code.pages) {
      files[page.path] = page.code
    }
  }

  // Add generated API route files
  if (code.apiRoutes) {
    for (const route of code.apiRoutes) {
      files[route.path] = route.code
    }
  }

  return files
}

/**
 * Get the list of files that would be included in the scaffold
 * (for preview purposes, without the actual code content).
 */
export function getScaffoldFileList(code: GeneratedCodeOutput): string[] {
  const configFiles = [
    'package.json',
    'tsconfig.json',
    'next.config.ts',
    'tailwind.config.ts',
    'postcss.config.mjs',
    '.env.example',
    'README.md',
    'src/app/globals.css',
    'src/app/layout.tsx',
  ]

  const generatedFiles = [
    ...(code.components?.map(c => c.path) || []),
    ...(code.pages?.map(p => p.path) || []),
    ...(code.apiRoutes?.map(r => r.path) || []),
  ]

  return [...configFiles, ...generatedFiles]
}
