import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Security",
  description:
    "How FHIRBuilders handles secrets, sandbox isolation, FHIR data, and incident response. Real practices, not boilerplate.",
};

const LAST_UPDATED = "2026-06-05";

export default function SecurityPage() {
  return (
    <div className="container mx-auto max-w-3xl px-4 py-12 lg:px-8 lg:py-16">
      <header className="mb-10 border-b border-slate-200 pb-6">
        <p className="mb-2 text-xs uppercase tracking-widest text-slate-500">Security</p>
        <h1 className="text-3xl font-bold tracking-tight text-slate-900 sm:text-4xl">
          How we handle the dangerous parts.
        </h1>
        <p className="mt-3 text-sm text-slate-600">
          Last updated <time dateTime={LAST_UPDATED}>{LAST_UPDATED}</time>. This page describes
          actual practice — not policy boilerplate. Found something concerning?{" "}
          <a className="underline" href="mailto:eugene.vestel@gmail.com">
            eugene.vestel@gmail.com
          </a>
          .
        </p>
      </header>

      <article className="prose prose-slate max-w-none prose-headings:mt-10 prose-headings:mb-3 prose-h2:text-xl prose-h2:font-semibold prose-p:my-3 prose-li:my-1">
        <h2>The big rule: no real PHI on FHIRBuilders. Ever.</h2>
        <p>
          FHIRBuilders is a sandbox + learning environment. We connect to FHIR servers
          (Medplum) pre-loaded with <strong>synthetic patient data only</strong>, generated by{" "}
          <a href="https://synthetichealth.github.io/synthea/" rel="noopener noreferrer" target="_blank">
            Synthea
          </a>
          . Real Protected Health Information (PHI) is not allowed in any sandbox you create
          here, in any project you share, or in any prompt you send through our AI features.
        </p>
        <p>
          When you start a cohort or accept a sandbox invite, you agree to this in writing. If
          we discover real PHI in a sandbox, we lock the sandbox, notify you, and (depending on
          severity) delete it within 24 hours.
        </p>

        <h2>What lives where</h2>
        <ul>
          <li>
            <strong>Application database:</strong> PostgreSQL on Neon (US region). TLS in
            transit. AES-256 at rest. Encrypted automatic backups, point-in-time recovery
            enabled.
          </li>
          <li>
            <strong>Application hosting:</strong> Vercel serverless functions + edge middleware,
            US regions. No long-lived servers we operate.
          </li>
          <li>
            <strong>Secrets:</strong> environment variables stored in Vercel project settings,
            scoped per environment (production / preview / development). The bot tokens for
            Slack cohort scripts (<code>SLACK_BOT_TOKEN</code>) live only in the operator&apos;s
            shell — we don&apos;t commit them to <code>.env</code> files (see CLAUDE.md security
            notes).
          </li>
          <li>
            <strong>FHIR clinical data:</strong> stays in your{" "}
            <a href="https://www.medplum.com" rel="noopener noreferrer" target="_blank">
              Medplum
            </a>{" "}
            project. We never proxy or cache FHIR resources on our servers.
          </li>
          <li>
            <strong>AI prompts:</strong> when you use OpenClaw or AI features, calls go directly
            to Anthropic / OpenAI under your own API key (BYOK). We store generation metadata
            (channel ID, status, token counts) — not prompt/response bodies.
          </li>
        </ul>

        <h2>Authentication</h2>
        <ul>
          <li>
            <strong>Sign-in:</strong> NextAuth.js v5 with GitHub OAuth, Google OAuth, Resend
            magic links, and bcrypt-hashed email/password. JWT sessions, signed with{" "}
            <code>NEXTAUTH_SECRET</code> (rotated when team membership changes).
          </li>
          <li>
            <strong>OAuth account linking:</strong> we explicitly allow linking GitHub and
            Google accounts that share a verified email (<code>allowDangerousEmailAccountLinking</code>),
            so signing in with either lands you on the same account. We rely on the providers
            to verify the email before linking — see the note in our code referencing that flag.
          </li>
          <li>
            <strong>Bcrypt:</strong> password hashes use bcrypt with cost 10. We never see your
            plaintext password.
          </li>
          <li>
            <strong>Edge middleware:</strong> <code>/dashboard</code>, <code>/profile</code>,
            <code>/admin</code>, and <code>/cohort/*</code> routes are protected by middleware
            that verifies the JWT before any handler runs.
          </li>
          <li>
            <strong>Admin pages:</strong> gated by an explicit allowlist
            (<code>ADMIN_EMAILS</code>) on top of normal sign-in. Compromising any cohort
            member&apos;s account does <em>not</em> grant access to the admin roster.
          </li>
        </ul>

        <h2>Sandbox isolation</h2>
        <p>
          Each sandbox is a Medplum project owned by the user who created it. We don&apos;t
          cross-mount data between sandboxes. Sample patients are seeded from Synthea modules
          you select; you can wipe and re-seed at any time.
        </p>
        <p>
          AI generation (OpenClaw) runs in isolated channels — each generation gets a fresh
          MessagingChannel + AppChannel record. Generated apps are stored as code artifacts only;
          we don&apos;t auto-execute them on our servers.
        </p>

        <h2>What we monitor</h2>
        <ul>
          <li>Vercel function logs (errors only) — retained per Vercel&apos;s defaults.</li>
          <li>Neon query logs and connection counts.</li>
          <li>
            Sign-in events (timestamp + count per user) — used for the admin roster, not for
            behavioral analytics.
          </li>
        </ul>
        <p>We don&apos;t run general-purpose user behavior analytics.</p>

        <h2>Vulnerability disclosure</h2>
        <p>
          Found a bug or vulnerability? Email{" "}
          <a className="underline" href="mailto:eugene.vestel@gmail.com">
            eugene.vestel@gmail.com
          </a>{" "}
          with steps to reproduce. We&apos;ll respond within 48 hours and credit you in the
          fix commit if you want.
        </p>
        <p>
          Please don&apos;t run automated scanners against production. The sandbox is meant for
          experimentation — feel free to break things in your own Medplum project.
        </p>

        <h2>Past incidents</h2>
        <ul>
          <li>
            <strong>2026-05-XX — exposed Neon credential in a settings file.</strong>{" "}
            <code>.claude/settings.local.json</code> committed in an early commit contained the
            Neon DATABASE_URL token. Neon flagged it; we rotated the role password the same
            day, made the file <code>.gitignore</code>&apos;d, and verified the old token was
            dead. No data accessed. See <code>CLAUDE.md</code> in the repo for the rotation
            playbook.
          </li>
        </ul>
        <p>
          We&apos;ll document any future incident here within 72 hours of discovery, even if no
          data was accessed.
        </p>

        <h2>Cohort consent + quiz</h2>
        <p>
          Before each cohort, builders complete a short security quiz + consent form covering
          the &ldquo;no real PHI&rdquo; rule, sandbox isolation, and the BYOK model. The quiz
          flow lives at{" "}
          <Link className="underline" href="/cohort/cohort-00/prereqs">
            /cohort/cohort-00/prereqs
          </Link>{" "}
          (rolling out the week of Session 1). You can&apos;t skip it — the cohort sub-routes
          gate on its completion once it ships.
        </p>

        <h2>Compliance posture</h2>
        <p>
          FHIRBuilders is <strong>not</strong> currently HIPAA-covered or SOC 2 certified — we
          stay out of the regulated space deliberately by accepting only synthetic data.
          Operating as an individual, not a corporate entity, as of {LAST_UPDATED}.
        </p>

        <h2>Contact</h2>
        <p>
          Eugene Vestel — <a className="underline" href="mailto:eugene.vestel@gmail.com">eugene.vestel@gmail.com</a>.
          For privacy questions specifically, see{" "}
          <Link className="underline" href="/privacy">
            /privacy
          </Link>
          .
        </p>
      </article>

      <footer className="mt-12 border-t border-slate-200 pt-6 text-xs text-slate-500">
        See also: <Link className="underline" href="/privacy">Privacy Policy</Link>. Last updated{" "}
        <time dateTime={LAST_UPDATED}>{LAST_UPDATED}</time>.
      </footer>
    </div>
  );
}
